services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn prin_site.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - staticfiles:/home/app/staticfiles  # save static files to a 'staticfile' volume, shared with nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.local`) && PathPrefix(`${SCRIPT_NAME}`)"
      - "traefik.http.routers.app.tls=false"
      - "traefik.http.routers.app.tls.certresolver=letsEncryptResolver"
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: nginx_static_files
    restart: always
    expose:
      - 1337
    volumes:
        - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
        - staticfiles:/static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`app.local`) && PathPrefix(`${SCRIPT_NAME}/static`)"
      - "traefik.http.routers.nginx.tls=false"
      - "traefik.http.routers.nginx.tls.certresolver=letsEncryptResolver"
      - "traefik.http.services.nginx.loadbalancer.server.port=1337"
  reverse-proxy:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./server/traefik.yml:/etc/traefik/traefik.yml"
      - "./server/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml"
      - "./server/acme.json:/acme.json"
      - "./logs:/var/log/traefik"
  db:
    image: neo4j:5.14.0
    restart: always
    container_name: neo4j_database
    expose:
      - 7474:7474
      - 7687:7687
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/data
      # install apoc to auto import data
      - ./server/database/plugins:/plugins:rw
      # mount import folder
      - ./server/database/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/${DATABASE_PASSWORD}
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      # auto import configuration
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_initializer_neo4j_1=CALL apoc.cypher.runSchemaFile("file:////var/lib/neo4j/import/indexes.cypher")
      - NEO4J_apoc_initializer_neo4j_2=CALL apoc.cypher.runFile("file:////var/lib/neo4j/import/schema.cypher");
volumes:
  datadir:
  staticfiles:
